// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UOpp8Fnq9UbZQkZ5RdHZnIPwHbsy790',
    appId: '1:125157695497:web:8f1d0a266d090938fad8d8',
    messagingSenderId: '125157695497',
    projectId: 'ultimate-cap',
    authDomain: 'ultimate-cap.firebaseapp.com',
    databaseURL: 'https://ultimate-cap-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-cap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZMIhpC7tzLRSWurOUha5X-VeUrNArPDo',
    appId: '1:125157695497:android:a5b734a1c038cbb9fad8d8',
    messagingSenderId: '125157695497',
    projectId: 'ultimate-cap',
    databaseURL: 'https://ultimate-cap-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-cap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MKXvC1v9wajMW037k3z1vr_lnu2MXEA',
    appId: '1:125157695497:ios:505c9bb10b071646fad8d8',
    messagingSenderId: '125157695497',
    projectId: 'ultimate-cap',
    databaseURL: 'https://ultimate-cap-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-cap.appspot.com',
    iosClientId: '125157695497-43e4ni9upiual342ji8kjk54fihcgrk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.capPh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MKXvC1v9wajMW037k3z1vr_lnu2MXEA',
    appId: '1:125157695497:ios:505c9bb10b071646fad8d8',
    messagingSenderId: '125157695497',
    projectId: 'ultimate-cap',
    databaseURL: 'https://ultimate-cap-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-cap.appspot.com',
    iosClientId: '125157695497-43e4ni9upiual342ji8kjk54fihcgrk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.capPh',
  );
}
